#!/bin/bash -eu

source "$(dirname "$0")/common.sh"

port="$(qwen36 get http.port)"
host="$(qwen36 get http.host)"

extra_args=()

verbose="$(qwen36 get verbose)"
if [ "${verbose}" = "true" ]; then
  extra_args+=(--verbose)
fi

gpu_layers="$(qwen36 get gpu-layers)"
if [[ -z "$gpu_layers" ]]; then
  echo "gpu-layers snap option is not set"
  exit 1
fi

exec "$server/usr/local/bin/llama-server" \
--model "$MODEL_FILE" \
--mmproj "$MMPROJ_FILE" \
--port "$port" \
--host "$host" \
--n-gpu-layers "$gpu_layers" \
--ctx-size 262144 \
--no-mmap \
--fit on \
--temp 0.6 \
--top-p 0.95 \
--top-k 20 \
--min-p 0.00 \
"${extra_args[@]}" \
"$@"
