#!/bin/bash -eu

component_name=model-qwen36-35b-a3b-ud-q4-k-xl

model_filename=Qwen3.6-35B-A3B-UD-Q4_K_XL.gguf
model_path=$SNAP_COMPONENTS/$component_name/$model_filename
export MODEL_FILE=$model_path
